# Action space settings.
JOINT_ACTION_SCALE = 0.25
WHEEL_ACTION_SCALE = 5.0

# Observation space settings. 
STATE_HISTORY = 15
SHORT_HISTORY  = 3

# Event RNG settings.
CPU_POOL_BUCKET_SIZE = 256

# Curriculum settings.
ANGULAR_ERROR_SCALE = 1.0
CURRICULUM_ERROR_THRESHOLD_UP = 0.3
CURRICULUM_ERROR_THRESHOLD_DOWN = 1.2
JOINT_DEVIATE_SCALE_LEVELS = 10
JOINT_DEVIATE_MIN_FACTOR = 0.1
# ACTION_CURRICULUM_LEVELS = 10
# ACTION_CURRICULUM_MAX_SCALE = 2.0

# Base height scan settings.
BASE_HEIGHT_THRESHOLD = 0.35
