# Observation space settings. 
STATE_HISTORY = 15
SHORT_HISTORY  = 3

# Event RNG settings.
CPU_POOL_BUCKET_SIZE = 256

# Curriculum settings.
ANGULAR_ERROR_SCALE = 1.0
CURRICULUM_ERROR_THRESHOLD_UP = 0.3
CURRICULUM_ERROR_THRESHOLD_DOWN = 1.2
ACTION_CURR_LEVELS = 8
